version: "3"
services:
  app:
    build: .
    ports:
      - "8089:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=banhang

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: banhang
    ports:
      - "3307:3306"
